const events = [
  {
    id: 13,
    image: "./img/cutTheChase.jpeg",
    name: "Cut The Chase",
    department: "IT",
    url: "/cut-the-chase",
  },
  {
    id: 14,
    image: "./img/relayCode.jpeg",
    name: "Relay Code",
    department: "IT",
    url: "/relay-code",
  },
  {
    id: 15,
    image: "./img/sharkTank.jpeg",
    name: "Shark Tank CGPIT",
    department: "IT",
    url: "/shark-tank",
  },
  {
    id: 16,
    image: "./img/playWithCode.jpeg",
    name: "Play With Code",
    department: "IT",
    url: "/play-with-codes",
  },
  {
    id: 1,
    image: "./img/download.png",
    name: "Talent Race",
    department: "Chemical",
    url: "/talent-race",
  },
  {
    id: 2,
    image: "./img/paperCup.png",
    name: "Paper Cup Race",
    department: "CE",
    url: "/paper-cup-race",
  },
  {
    id: 3,
    image: "./img/ARQR HUNT.png",
    name: "AR / QR Hunt",
    department: "CE",
    url: "/ar-qr-hunt",
  },
  {
    id: 4,
    image: "./img/valoEvent.png",
    name: "Valorant Gaming Event ",
    department: "CE",
    url: "/valorant-gaming-event",
  },
  {
    id: 5,
    image: "./img/wtBalance.jpeg",
    name: "Weight Balancing",
    department: "CE",
    url: "/weight-balancing",
  },
  {
    id: 6,
    image: "./img/footballTicTacToe.png",
    name: "Football Tic Tac Toe",
    department: "CE",
    url: "/football-tic-tac-toe",
  },
  {
    id: 7,
    image: "./img/download.png",
    name: "उत्तरोत्तर",
    department: "civil",
    url: "/pehchano-kon",
  },
  {
    id: 8,
    image: "./img/download.png",
    name: "SCRAPPER  क्रैपर",
    department: "civil",
    url: "/make-from-scrap",
  },
  {
    id: 9,
    image: "./img/download.png",
    name: "TRESURE HUNT",
    department: "civil",
    url: "/tresure-hunt",
  },
  {
    id: 10,
    image: "./img/Mad_ads.png",
    name: "MAD ADS",
    department: "mech, mecha, auto",
    url: "/mad-ads",
  },
  {
    id: 11,
    image: "./img/Prove your.png",
    name: "PROVE YOUR ENGINEERING",
    department: "mech, mecha, auto",
    url: "/prove-your-engineering",
  },
  {
    id: 12,
    image: "./img/Tech_Team.png",
    name: "TEAM-TECH COORDINATION GAMES",
    department: "mech, mecha, auto",
    url: "/team-tech-coordination-games",
  },
];

export default events;
